/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsImageCompressorRouteImport } from './routes/tools.image-compressor'
import { Route as ToolsJpgToPdfRouteImport } from './routes/tools.jpg-to-pdf'
import { Route as ToolsPdfCompressorRouteImport } from './routes/tools.pdf-compressor'
import { Route as ToolsPdfMergeRouteImport } from './routes/tools.pdf-merge'
import { Route as ToolsQrCodeGeneratorRouteImport } from './routes/tools.qr-code-generator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsImageCompressorRoute = ToolsImageCompressorRouteImport.update({
  id: '/image-compressor',
  path: '/image-compressor',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsJpgToPdfRoute = ToolsJpgToPdfRouteImport.update({
  id: '/jpg-to-pdf',
  path: '/jpg-to-pdf',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPdfCompressorRoute = ToolsPdfCompressorRouteImport.update({
  id: '/pdf-compressor',
  path: '/pdf-compressor',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPdfMergeRoute = ToolsPdfMergeRouteImport.update({
  id: '/pdf-merge',
  path: '/pdf-merge',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsQrCodeGeneratorRoute = ToolsQrCodeGeneratorRouteImport.update({
  id: '/qr-code-generator',
  path: '/qr-code-generator',
  getParentRoute: () => ToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/jpg-to-pdf': typeof ToolsJpgToPdfRoute
  '/tools/pdf-compressor': typeof ToolsPdfCompressorRoute
  '/tools/pdf-merge': typeof ToolsPdfMergeRoute
  '/tools/qr-code-generator': typeof ToolsQrCodeGeneratorRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/jpg-to-pdf': typeof ToolsJpgToPdfRoute
  '/tools/pdf-compressor': typeof ToolsPdfCompressorRoute
  '/tools/pdf-merge': typeof ToolsPdfMergeRoute
  '/tools/qr-code-generator': typeof ToolsQrCodeGeneratorRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/jpg-to-pdf': typeof ToolsJpgToPdfRoute
  '/tools/pdf-compressor': typeof ToolsPdfCompressorRoute
  '/tools/pdf-merge': typeof ToolsPdfMergeRoute
  '/tools/qr-code-generator': typeof ToolsQrCodeGeneratorRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy-policy'
    | '/reset-password'
    | '/terms'
    | '/tools'
    | '/dashboard'
    | '/tools/image-compressor'
    | '/tools/jpg-to-pdf'
    | '/tools/pdf-compressor'
    | '/tools/pdf-merge'
    | '/tools/qr-code-generator'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy-policy'
    | '/reset-password'
    | '/terms'
    | '/dashboard'
    | '/tools/image-compressor'
    | '/tools/jpg-to-pdf'
    | '/tools/pdf-compressor'
    | '/tools/pdf-merge'
    | '/tools/qr-code-generator'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy-policy'
    | '/reset-password'
    | '/terms'
    | '/tools'
    | '/_authenticated/dashboard'
    | '/tools/image-compressor'
    | '/tools/jpg-to-pdf'
    | '/tools/pdf-compressor'
    | '/tools/pdf-merge'
    | '/tools/qr-code-generator'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/image-compressor': {
      id: '/tools/image-compressor'
      path: '/image-compressor'
      fullPath: '/tools/image-compressor'
      preLoaderRoute: typeof ToolsImageCompressorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/jpg-to-pdf': {
      id: '/tools/jpg-to-pdf'
      path: '/jpg-to-pdf'
      fullPath: '/tools/jpg-to-pdf'
      preLoaderRoute: typeof ToolsJpgToPdfRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/pdf-compressor': {
      id: '/tools/pdf-compressor'
      path: '/pdf-compressor'
      fullPath: '/tools/pdf-compressor'
      preLoaderRoute: typeof ToolsPdfCompressorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/pdf-merge': {
      id: '/tools/pdf-merge'
      path: '/pdf-merge'
      fullPath: '/tools/pdf-merge'
      preLoaderRoute: typeof ToolsPdfMergeRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/qr-code-generator': {
      id: '/tools/qr-code-generator'
      path: '/qr-code-generator'
      fullPath: '/tools/qr-code-generator'
      preLoaderRoute: typeof ToolsQrCodeGeneratorRouteImport
      parentRoute: typeof ToolsRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ToolsRouteChildren {
  ToolsImageCompressorRoute: typeof ToolsImageCompressorRoute
  ToolsJpgToPdfRoute: typeof ToolsJpgToPdfRoute
  ToolsPdfCompressorRoute: typeof ToolsPdfCompressorRoute
  ToolsPdfMergeRoute: typeof ToolsPdfMergeRoute
  ToolsQrCodeGeneratorRoute: typeof ToolsQrCodeGeneratorRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsImageCompressorRoute: ToolsImageCompressorRoute,
  ToolsJpgToPdfRoute: ToolsJpgToPdfRoute,
  ToolsPdfCompressorRoute: ToolsPdfCompressorRoute,
  ToolsPdfMergeRoute: ToolsPdfMergeRoute,
  ToolsQrCodeGeneratorRoute: ToolsQrCodeGeneratorRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
