// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const MOCK_CATEGORIES = [
  {
    id: "cat-pdf",
    name: "PDF Tools",
    slug: "pdf-tools",
    icon: "FileText",
    description: "Compress, merge, convert and manipulate PDF documents",
  },
  {
    id: "cat-image",
    name: "Image Tools",
    slug: "image-tools",
    icon: "Image",
    description: "Resize, optimize, crop and convert your image files",
  },
  {
    id: "cat-converters",
    name: "Converters",
    slug: "converters",
    icon: "RefreshCw",
    description: "Fast file and format conversion in your browser",
  },
  {
    id: "cat-generators",
    name: "Generators",
    slug: "generators",
    icon: "QrCode",
    description: "Instant QR code, barcode, and utility generators",
  },
  {
    id: "cat-developer",
    name: "Developer Tools",
    slug: "developer-tools",
    icon: "Code",
    description: "Formatting, encoding, and web developer essentials",
  },
];

const MOCK_TOOLS = [
  {
    id: "1",
    title: "PDF Compressor",
    slug: "pdf-compressor",
    description: "Reduce PDF file size while maintaining quality.",
    thumbnail_url: null,
    category_id: "cat-pdf",
    featured: true,
    views: 1420,
    status: "published",
  },
  {
    id: "2",
    title: "PDF Merge",
    slug: "pdf-merge",
    description: "Combine multiple PDF files into a single document.",
    thumbnail_url: null,
    category_id: "cat-pdf",
    featured: true,
    views: 980,
    status: "published",
  },
  {
    id: "3",
    title: "Image Compressor",
    slug: "image-compressor",
    description: "Compress images without noticeable quality loss.",
    thumbnail_url: null,
    category_id: "cat-image",
    featured: true,
    views: 1250,
    status: "published",
  },
  {
    id: "4",
    title: "JPG to PDF",
    slug: "jpg-to-pdf",
    description: "Convert JPG images into PDF documents.",
    thumbnail_url: null,
    category_id: "cat-converters",
    featured: true,
    views: 890,
    status: "published",
  },
  {
    id: "5",
    title: "QR Code Generator",
    slug: "qr-code-generator",
    description: "Generate custom QR codes instantly.",
    thumbnail_url: null,
    category_id: "cat-generators",
    featured: true,
    views: 1650,
    status: "published",
  },
];

function createMockSupabaseClient() {
  console.warn(
    "[Supabase] Supabase environment variables not configured. Using in-memory fallback client.",
  );

  function createQueryBuilder(tableName: string) {
    let items: Record<string, unknown>[] = [];
    if (tableName === "tool_categories") {
      items = [...MOCK_CATEGORIES];
    } else if (tableName === "tools") {
      items = [...MOCK_TOOLS];
    }

    let isSingle = false;
    let isMaybeSingle = false;

    type MockQueryBuilder = {
      select: (_cols?: string, _opts?: Record<string, unknown>) => MockQueryBuilder;
      eq: (field: string, val: unknown) => MockQueryBuilder;
      neq: (field: string, val: unknown) => MockQueryBuilder;
      or: (_term: string) => MockQueryBuilder;
      order: (field: string, opts?: { ascending?: boolean }) => MockQueryBuilder;
      limit: (n: number) => MockQueryBuilder;
      range: (from: number, to: number) => MockQueryBuilder;
      single: () => MockQueryBuilder;
      maybeSingle: () => MockQueryBuilder;
      insert: (_data: unknown) => MockQueryBuilder;
      update: (_data: unknown) => MockQueryBuilder;
      delete: () => MockQueryBuilder;
      then: (resolve: (val: unknown) => unknown) => Promise<unknown>;
    };

    const builder: MockQueryBuilder = {
      select(_cols?: string, _opts?: Record<string, unknown>) {
        return builder;
      },
      eq(field: string, val: unknown) {
        items = items.filter((item) => item[field] === val);
        return builder;
      },
      neq(field: string, val: unknown) {
        items = items.filter((item) => item[field] !== val);
        return builder;
      },
      or(_term: string) {
        return builder;
      },
      order(field: string, opts?: { ascending?: boolean }) {
        const asc = opts?.ascending !== false;
        items.sort((a, b) => {
          const valA = a[field];
          const valB = b[field];
          if (typeof valA === "number" && typeof valB === "number") {
            return asc ? valA - valB : valB - valA;
          }
          return asc
            ? String(valA ?? "").localeCompare(String(valB ?? ""))
            : String(valB ?? "").localeCompare(String(valA ?? ""));
        });
        return builder;
      },
      limit(n: number) {
        items = items.slice(0, n);
        return builder;
      },
      range(from: number, to: number) {
        items = items.slice(from, to + 1);
        return builder;
      },
      single() {
        isSingle = true;
        return builder;
      },
      maybeSingle() {
        isMaybeSingle = true;
        return builder;
      },
      insert(_data: unknown) {
        return builder;
      },
      update(_data: unknown) {
        return builder;
      },
      delete() {
        return builder;
      },
      then(resolve: (val: unknown) => unknown) {
        const total = items.length;
        if (isSingle || isMaybeSingle) {
          return Promise.resolve(resolve({ data: items[0] ?? null, error: null, count: total }));
        }
        return Promise.resolve(resolve({ data: items, error: null, count: total }));
      },
    };

    return builder;
  }

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      onAuthStateChange: () => ({
        data: { subscription: { unsubscribe: () => {} } },
      }),
      signInWithPassword: async () => ({
        data: { user: null, session: null },
        error: new Error("Authentication requires connecting Supabase."),
      }),
      signUp: async () => ({
        data: { user: null, session: null },
        error: new Error("Authentication requires connecting Supabase."),
      }),
      signOut: async () => ({ error: null }),
      resetPasswordForEmail: async () => ({ data: {}, error: null }),
    },
    from: (table: string) => createQueryBuilder(table),
  } as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return createMockSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
